### ISSUE TITLE
TypeError: sf.getLineAndCharacterOfPosition is not a function

### ISSUE THREAD

**Issue by jewelpit** [dropbox/ts-transform-react-jsx-source#258]
When running with TypeScript 4.0.3, ts-jest 26.4.4, and ts-loader 8.0.11, I get the following error during compilation:

`TypeError: sf.getLineAndCharacterOfPosition is not a function`

I logged the keys of `sf` during transformation, and it looks like it has every `typescript.SourceFile` field except for `getLineAndCharacterOfPosition`. Is this a known issue when using newer versions of ts-jest and ts-loader?

**Comment by longlho** [comment]
Thank you for letting us know. TS4 does have a slightly different compiler api. We'll fix this soon.

**Comment by longlho** [comment]
closed in cb9c8472d1a2fd89ff7b23179bb53c9e72405d8c

**Comment by longlho** [comment]
`ts-transform-react-jsx-source@2.0.0` should have this fix
